spring:
  config:
    import: "optional:file:../.env[.properties],optional:file:.env[.properties]"
  application:
    name: crm

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/crm}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
