name: 'CI'

on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  todo:
    name: TODO
    runs-on: ubuntu-24.04
    steps:
      - name: TODO
        run: echo "TODO"